### ISSUE TITLE
px-preview does not work (too many arguments for in px--create-preview)

### ISSUE THREAD

**Issue by EvgeniiFrolov** [aaptel/preview-latex#1]
Today I've installed the package. Should say, I've used it a lot before this
summer and thanks a lot for it!

However, px installation with emacs package management system gave me

---

Compiling file ~/.emacs.d/elpa/px-20141006.548/px.el at Sat Aug 22 14:37:19 2015

In px--create-preview:
px.el:65:4:Warning: org-format-latex called with 7 arguments, but accepts only
    1-6

---

and using the function px-preview gave me

---

px--create-preview: Wrong number of arguments: #[(prefix &optional dir overlays msg forbuffer processing-type) "SOMEBINARYSTUFF" [overlays processing-type math-regexp cnt checkdir-flag context fboundp clear-image-cache verbatim "\$\|\\[([]\|^[     ]_\\begin{[A-Za-z0-9_]+}" ...] 11 ("/home/ef/.emacs.d/elpa/org-20150810/org.elc" . 641900)], 7

---

After changing

---

(defun px--create-preview (at)
  "Wrapper for `org-format-latex'.
The parameter AT should be nil or in (TYPE . POINT) format.  With TYPE being a
string showing the matched LaTeX statement (e.g.,``$'') and POINT being the
POINT to replace.  If AT is nil replace statements everywhere."
  (org-format-latex px-temp-file-prefix
                    px-temp-dir
                    'overlays
                    "Creating images...%s"
                    **at 'forbuffer**
                    px-image-program))

---

to

---

(defun px--create-preview (at)
  "Wrapper for `org-format-latex'.
The parameter AT should be nil or in (TYPE . POINT) format.  With TYPE being a
string showing the matched LaTeX statement (e.g.,``$'') and POINT being the
POINT to replace.  If AT is nil replace statements everywhere."
  (org-format-latex px-temp-file-prefix
                    px-temp-dir
                    'overlays
                    "Creating images...%s"
                    **'forbuffer**
                    px-image-program))

---

recompilation and reloading of px.elc
**everything works!**

This is my first kinda-bug-report for emacs package, so tell me please if I have
chosen a right path to deal with a bug!

**Comment by aaptel** [comment]
The proper fix would be to either:
- check which version of org is installed and use the `org-format-latex` function differently depending on that
- bump the org version requirement and only use the newer `org-format-latex`

First solution is better, second is simpler. Both are acceptable. I'll review/accept any pull request you send my way :)

**Comment by EvgeniiFrolov** [comment]
ok, I've done the request! 
So exited) My first one!
Did I do everything as supposed to be according to git-hub-collaboration way?)

**Comment by EvgeniiFrolov** [comment]
Hello! Have you possibly managed to check the issue?

**Comment by aaptel** [comment]
Hi, sorry for handling this so late...

So I've looked at the issue more carefully:

- the current code works on my setup
- `org-format-latex` changed from having 6 to 7 arguments starting from emacs v23.1, which came out in 2009.

I find it strange that your fix works since you shifted the parameters by one but they don't mean the same thing :suspect:... I'm too lazy to test on older emacs so I will just add a condition and call it your way if the function only has 6 args.

**Comment by EvgeniiFrolov** [comment]
well... thank you for the attention and for the package)
